version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn djangocongress.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    depends_on:
      - db
  nginx:
    build:
        context: ./config/nginx
        dockerfile: Dockerfile
    expose:
        - "8000"
    ports:
      - "8000:8000"
    volumes:
        - static_volume:/code/staticfiles
    depends_on:
        - web

volumes:
    static_volume:
